apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cookbookbo-api
  name: cookbookbo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookbookbo-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cookbookbo-api
    spec:
      containers:
      - image: jevillanueva/cookbookbo-api:latest
        name: cookbookbo-api
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        envFrom:
          - secretRef:
              name: cookbookbo-api
        volumeMounts:
          - name: cookbookbo-api-gcp-storage
            mountPath: /app/keys
            readOnly: true
        resources: {}
      volumes:
        - name: cookbookbo-api-gcp-storage
          secret:
            secretName: cookbookbo-api-gcp-storage
status: {}
